Develop
Taraxa-project/hype pull request #13
Opened 2022-05-19 15:06 UTC by VargaElod23

2022-05-25 22:45 UTC, farebord requested changes

2022-05-25 22:45 UTC, farebord commented on src/components/card/Card.tsx
> +  .container {
I think it will be better to split these children's containers into new styled components. 
One of the reasons of this is that it allows easier refactoring if these children became reusable over time.
Another reason will be that is more readable to create one styled component per HTML element we add to the component.

2022-05-25 22:45 UTC, farebord commented on src/components/card/Card.tsx
> +  .dataContainer {
Same as the above suggestion.

2022-05-25 22:45 UTC, farebord commented on src/components/card/Card.tsx
> +  .dataHeader {
Same as the above suggestion.

2022-05-25 22:45 UTC, farebord commented on src/components/card/Card.tsx
> +  .dataValue {
Same as the above suggestion.

2022-05-25 22:45 UTC, farebord commented on src/components/card/Card.tsx
> +  line-height: 20px;
We are using rem units with the default font size of 16px. You can use this tool for converting pixel units to rem units https://nekocalc.com/es/px-a-rem-conversor.

2022-05-25 22:45 UTC, farebord commented on src/components/header/Header.tsx
> +  .headerRight {
Same as the above suggestion.

2022-05-25 22:45 UTC, farebord commented on src/components/header/Header.tsx
> +    const isMobile = useMediaQuery({ query: `(max-width: 760px)` });
I think we can handle mobile just by using `styled-components` media queries. 
As an example:

```
const CardWrapper = styled.div`
  display: flex;
  flex-direction: row;
  @media (max-width: 768px) {
    flex-direction: column;
  }
`;
```
If we use this approach we don't need to use custom hooks.

2022-05-25 22:45 UTC, farebord commented on src/components/header/Header.tsx
> +    console.log("Ehtereum", window);
Remove this `console.log`

2022-05-26 07:33 UTC, VargaElod23 commented on src/components/header/Header.tsx
> +    const isMobile = useMediaQuery({ query: `(max-width: 760px)` });
Yeah, I wanted to go for that implementation too, but then how are you showcasing these in the storybook? A lot of these configs needed to be exposed as props just for us to have a way to show them in the storybook

2022-05-26 07:39 UTC, Elod23 commented on src/components/card/Card.tsx
> +  .container {
Let's keep this thread open

2022-05-26 14:49 UTC, farebord requested changes

2022-05-26 14:49 UTC, farebord commented on src/components/input/Input.tsx
> +  border-radius: 12px;
We should use rem instead of px

2022-05-26 14:49 UTC, farebord commented on src/components/input/Input.tsx
> +    border: 2px solid #EB8F4C !important;
Same as above suggestion

2022-05-26 15:27 UTC, farebord requested changes

2022-05-26 15:27 UTC, farebord commented on src/components/header/Header.tsx
> +    height: 6px !important;
We should use rem instead of px.

2022-05-26 15:27 UTC, farebord commented on src/components/input/Input.tsx
> +  border: 1px solid #e0e0e0;
We should use rem instead of px.

2022-06-22 11:36 UTC, closed without merging