#128 Add tests for components (WIP)
Taraxa-project/hype pull request #131
Opened 2022-07-19 13:57 UTC by farebord

https://github.com/Taraxa-project/hype/issues/128

Please link the issue:

Fixes #128 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2022-07-25 06:47 UTC, Malak67 commented on services/client/src/testUtils.tsx
> +const AllTheProviders: FC<{ children: React.ReactNode }> = ({ children }) => {
@farebord Why do we need this file? Are we using it?
I don't see it used anywhere. Maybe it is left from the wagmi tests.

2022-07-25 06:47 UTC, Malak67 approved these changes
LGTM! Left one minor comment.

!!! Please pull develop and fix merge issues before merging this branch.

2022-07-25 08:11 UTC, VargaElod23 requested changes
Please fix conflicts and add the test runs into the workflow when changes are made to the frontend like it is for the contract unit tests.

2022-07-25 13:53 UTC, farebord commented on services/client/src/testUtils.tsx
> +const AllTheProviders: FC<{ children: React.ReactNode }> = ({ children }) => {
It's been used on every test. It's a wrapper that adds hypetheme to it.
`import { render, screen } from 'src/testUtils';`

Check imports.

2022-07-26 14:44 UTC, VargaElod23 approved these changes

2022-07-26 14:44 UTC, merged