Feature/145/smart contract ipfs update
Taraxa-project/hype pull request #148
Opened 2022-07-27 13:22 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

Closes #145 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Added logic to handle IPFS url in Hype Pool Contract

## Funny gif

Leave a funny gif for faster review.

2022-07-27 14:20 UTC, Elod23 requested changes
Can you please explain why do we need the flow below?

2022-07-27 14:25 UTC, Elod23 requested changes

2022-07-27 14:25 UTC, Elod23 commented on packages/contracts/contracts/interfaces/IHypePool.sol
> +        string projectName,
I'd say to keep the uri here because we're going to need that inside the event to not fetch the contract once again for it.

2022-07-27 18:04 UTC, Malak67 commented
@Elod23 I implemented the changes you mentioned and adjusted the tests as well. All it's left it's deploying it.

2022-07-28 07:52 UTC, VargaElod23 approved these changes
LGTM. 🚀 deplooy time

2022-07-28 08:28 UTC, merged