Feature/set up claim backend
Taraxa-project/hype pull request #169
Opened 2022-11-18 14:33 UTC by VargaElod23

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2022-11-22 13:15 UTC, VargaElod23 commented on services/hype-backend/src/modules/reward/reward.controller.ts
> +      return await this.rewardService.accrueRewards(rewardToAccrue);
Comment this endpoint for now

2022-11-22 13:17 UTC, VargaElod23 commented on services/hype-backend/src/modules/reward/reward.service.ts
> +        address,
Take only the unclaimed.

2022-12-05 10:41 UTC, Malak67 requested changes
Small changes needed

2022-12-05 10:41 UTC, Malak67 commented on services/hype-backend/src/modules/reward/reward.service.ts
> +    const rewardsOfAddress = await this.rewardRepository.findBy({
Maybe add an exception below this. If (rewardsOfAddress?.length === 0) { throw new NotFoundException()} or something similar, before using the .filter on it.

2022-12-05 10:41 UTC, Malak67 commented on services/hype-backend/src/modules/reward/reward.service.ts
> +    const rewardsOfAddress = await this.rewardRepository.findBy({
Saw you added this check on the next method, so you can add it here as well.

2022-12-05 10:41 UTC, Malak67 commented on services/hype-backend/src/modules/reward/reward.controller.ts
> +    description: 'Returns a newly inserted pool reward',
description needs to be updated

2022-12-05 10:41 UTC, Malak67 commented on services/hype-backend/src/modules/reward/reward.controller.ts
>    @Post()
I think we should have some authorization on these endpoints. For now you can add `@UseGuards(WalletGuard)` and afterwards we will see if we should add another custom guard.

2022-12-06 11:54 UTC, Malak67 approved these changes

2022-12-06 13:00 UTC, merged