Add mobile sidebar.
Taraxa-project/hype pull request #18
Opened 2022-05-26 19:43 UTC by farebord

2022-05-30 15:20 UTC, VargaElod23 commented
Is it just me or the header elements are squashed now? 
![image](https://user-images.githubusercontent.com/100562086/171022186-9de65f18-56fe-49a3-bda1-e7704059ffe0.png)

2022-05-30 15:22 UTC, VargaElod23 requested changes
Code looks good, 1 small suggestion and please take a look at the header element styling issue on the comment above.

2022-05-30 15:22 UTC, VargaElod23 commented on src/components/header/Header.stories.tsx
> +  account: "0x6e3AA...82aFB",
Here we should inject the full account and make the component standardize it with the MM stnadard: `5 chars ... 4 chars`

2022-05-31 16:21 UTC, farebord commented on src/components/header/Header.stories.tsx
> +  account: "0x6e3AA...82aFB",
Ohh I see! I thought it came as 5chars ... 4 chars as default. @VargaElod23 Should it be `0x12345...1234` ?

2022-05-31 16:22 UTC, Elod23 commented on src/components/header/Header.stories.tsx
> +  account: "0x6e3AA...82aFB",
0x123...4567

2022-05-31 19:24 UTC, VargaElod23 approved these changes
👍🏼

2022-05-31 19:24 UTC, merged