Feature/homepage
Taraxa-project/hype pull request #19
Opened 2022-05-27 11:43 UTC by VargaElod23

2022-05-30 14:43 UTC, VargaElod23 commented on client/src/pages/Home/Home.tsx
> +import InfiniteScroll from "react-infinite-scroll-component";
@farebord @rattrap

2022-05-31 19:32 UTC, farebord commented on client/src/App.css
> +  border-radius: 32px;
```suggestion
  border-radius: 2rem;
```

2022-05-31 19:33 UTC, farebord commented on client/src/components/input/Input.tsx
> +  padding: 10px;
```suggestion
  padding: 0.625rem;
```

2022-05-31 19:34 UTC, farebord commented on client/src/pages/Home/Home.css
> +  font-size: 24px;
```suggestion
  font-size: 1.5rem;
```

2022-05-31 19:37 UTC, farebord commented on client/src/pages/Home/Home.tsx
> +import "./Home.css";
We are avoiding CSS modules on hype. Could you write styled-components instead?

2022-05-31 19:38 UTC, farebord requested changes
Left multiple changes requested.

2022-06-01 22:46 UTC, farebord requested changes

2022-06-01 22:46 UTC, farebord commented on client/src/pages/Home/Home.tsx
> +import "./Home.css";
For that case you can use:
```
const StyledInfiniteScroll = styled(InfiniteScroll)`
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    justify-content: space-evenly;
    margin-top: 1rem;
    margin-bottom: 3rem;
    overflow: auto;
`;
```

For the description it can be replaced with:
```
const Description = styled.span`
  font-weight: 400;
  font-size: 14px;
  line-height: 20px;

  letter-spacing: -0.02em;
  text-align: left;
  color: #595959;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  max-width: 15rem;
  overflow: hidden;
  text-overflow: ellipsis;
`;
```
Also, don't forget to change them to `rem` 😅 
And I think there are few other classes to convert.

2022-06-02 14:10 UTC, merged