Feat/update contracts
Taraxa-project/hype pull request #194
Opened 2023-05-10 17:21 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-07-25 13:23 UTC, VargaElod23 requested changes
I'd advise you to consider:

- Refactor requires as Errors for better readability and gas optimization
- Reimplement the leaderboard rewards as array
- Clean up the Slither errors one-by-one and think about whether they have some impact on our business logic or not because most of them are valid concerns they just have limited impact on our business logic.
- If the architecture and implementation has been agreed upon, we should switch to use the upgradable ones as the main contracts soon.


I also have some doubts about how

2023-07-25 13:23 UTC, VargaElod23 commented on packages/contracts/contracts/interfaces/IHypePool.sol
> +        uint256 firstLeaderRewards;
I don't particularly like this approach as I feel that this functionality is much more business-related than this strict implementation. 
 To be prepared for changes I'd keep this as an ordered array of values on each pool as `leaderboardRewards` that can be of flexible length and that gives freedom to all parties to provide as many additional rewards to as many first places as possible. For now I know we need just 3,  but it might be worth to think about.

2023-07-26 11:17 UTC, guibvieira reviewed
Looks good!! After reviewing I think I left some comments that were repeated from Elod in the end. Some additional checks for erc allowances and I think we should have a dynamic array for the rewards as I think this will change with high likelihood so we should prepare for that. Some getters I think could also do with some requires just so there is an error message if they error out :)

2023-07-26 22:10 UTC, Malak67 commented on packages/contracts/contracts/HypePoolBase.sol
> +        _pool.rewards.endDate = block.timestamp;
Good point. Changed this!

2023-07-26 22:11 UTC, Malak67 commented on packages/contracts/contracts/DynamicEscrow.sol
> +            ECDSA.recover(hash, sig) == _trustedAccountAddress,
Yes, the nonce and hash get generated from the backend in order to claim, based on a specific private key which should match the trustedAccountAddress here.

2023-07-27 13:25 UTC, guibvieira commented on packages/contracts/contracts/HypePoolBase.sol
> +        _pool.rewards.endDate = block.timestamp - 7 days;
This is a good solution to the issue before. Was just wondering if the following could be a side effect. If a pool is deactivated, endDate is pushed 7 days back which will mean the gracePeriod ends in the desired endDate. Does this affect the data coming from graphQL query? Will the analytics pipeline then see an endDate - 7 days or the actual endDate? Or will the endDate remain as the original endDate? Worried about the analytics layer then not considering that last week because of this

2023-07-31 13:04 UTC, VargaElod23 approved these changes

2023-07-31 13:09 UTC, VargaElod23 approved these changes

2023-08-01 09:19 UTC, rattrap requested changes

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +    mapping(bytes32 => string) private _tokenURIs;
Let's just store this in the `HypePool`

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +    mapping(bytes32 => bool) private _hashes;
Don't need this. We can check the creator address in `HypePool`

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +        _emitPoolRewards(uuid, rewards, leaderRewards);
Let's just move these events inline

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +        _setPoolURI(uuid, uri);
We can move this to the `_setPool` method

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +        require(_pool.rewards.impressionReward != 0, "Pool doesn't exist");
Here we use another method to check if it exists

2023-08-01 09:19 UTC, rattrap commented on packages/contracts/contracts/HypePoolBase.sol
> +        require(_pool.rewards.impressionReward != 0, "Pool doesn't exist");
Same. Using another check

2023-08-02 07:45 UTC, VargaElod23 approved these changes

2023-08-02 10:16 UTC, rattrap approved these changes

2023-08-02 15:10 UTC, merged