Proper handle API errors
Taraxa-project/hype pull request #232
Opened 2023-06-15 20:27 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.
![image](https://github.com/Taraxa-project/hype/assets/9773044/b064845a-4f1d-4ef5-bc6a-96ed4c774b93)

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-06-15 20:29 UTC, Malak67 commented
Ignore the Big red button behind the modal. That was used just to test the POST action.

2023-06-16 11:07 UTC, VargaElod23 requested changes

2023-06-16 11:07 UTC, VargaElod23 commented on services/client/src/api/auth/useLogin.tsx
> +        const errorData = error as AxiosError;
You do this basically on all files. It would be great to extract it into a util func that also handles optionals, and then  we can get rid of the ugly `?`s

2023-06-16 13:58 UTC, VargaElod23 approved these changes

2023-06-20 14:48 UTC, rattrap approved these changes

2023-06-20 14:48 UTC, merged