Added impressions to reward
Taraxa-project/hype pull request #233
Opened 2023-06-19 11:11 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-06-19 14:10 UTC, VargaElod23 approved these changes
LGTM

2023-06-20 14:54 UTC, rattrap requested changes

2023-06-20 14:54 UTC, rattrap commented on services/hype-backend/src/entities/reward.entity.ts
> +  IsNumber,
Don't see this used

2023-06-20 14:54 UTC, rattrap commented on services/hype-backend/src/migrations/1687179992085-RewardClaimAssociation.ts
> +import { MigrationInterface, QueryRunner } from 'typeorm';
I would use `_` for column names. In the app you can then specify the column name using annotations

2023-06-20 15:22 UTC, merged