Added endpoints for pool stats and pool leaderboard
Taraxa-project/hype pull request #236
Opened 2023-06-21 13:45 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-06-22 08:59 UTC, VargaElod23 requested changes
Single logic question added

2023-06-22 08:59 UTC, VargaElod23 commented on services/hype-backend/src/modules/reward/reward.service.ts
> +        tokensAwarded += amount;
Shouldn't this be reversed? if claimed add to claimed

2023-06-22 09:56 UTC, Malak67 commented on services/hype-backend/src/modules/reward/reward.service.ts
> +        tokensAwarded += amount;
This is true for the reward entity. But we are using the claim entity. The field claimed = true means the user has claimed from the contract and got the reward.

2023-06-22 13:43 UTC, rattrap requested changes

2023-06-22 13:43 UTC, rattrap commented on services/hype-backend/src/modules/reward/pools.controller.ts
> +  @ApiBearerAuth('authorization')
Don't need auth for this.

2023-06-22 13:43 UTC, rattrap commented on services/hype-backend/src/modules/reward/pools.controller.ts
> +  @ApiBearerAuth('authorization')
Don't need auth for this.

2023-06-22 13:43 UTC, rattrap commented on services/hype-backend/src/modules/reward/reward.service.ts
> +}
Why do need this? We can just use the DTO

2023-06-22 13:43 UTC, rattrap commented on services/hype-backend/src/modules/reward/reward.service.ts
> +    const claims = await this.claimRepository.find({ where: { poolId } });
This is wrong. We should look in `rewards`, not claims

2023-06-22 13:43 UTC, rattrap commented on services/hype-backend/src/modules/reward/reward.service.ts
> +    };
Rewards are in the thousands at least. We shouldn't interate over them.
Let's just do two queries:
- distinct telegram id count
- sum(impressions)

2023-06-23 09:25 UTC, rattrap approved these changes

2023-06-23 10:16 UTC, merged