Added changes to support image upload
Taraxa-project/hype pull request #237
Opened 2023-06-22 10:09 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #<33>.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-06-26 09:53 UTC, VargaElod23 requested changes

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/api/pools/useFetchHypePools.tsx
> +  orderBy: string;
here it might make sense to limit the choices to the fields that make sense as a type: 
```suggestion
  orderBy: 'endDate' | 'startDate' | ... ;
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/api/pools/useFetchHypePools.tsx
> +  orderDirection: string;
```suggestion
  orderDirection: 'desc' | 'asc' ;
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/components/card/Card.tsx
> +                {transformFromWei(cap, tokenDecimals)} {tokenName || 'TARA'}
We should cover this fallback when the `tokenName` is getting its value assigned, I believe
```suggestion
                {transformFromWei(cap, tokenDecimals)} {tokenName}
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/components/card/Card.tsx
> +                {tokenName || 'TARA'}
same

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/components/stats-card/StatsCard.styled.tsx
> +  background-color: ${({ theme }) => theme.colors.greys[2]};
I'd expect this to be the same color theme: since our CTAs are that orange, I think these would be more visible with white text on the same orange background 
![image](https://github.com/Taraxa-project/hype/assets/100562086/881cd6fd-6a9c-4598-9177-bd56e7250e12)

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/pages/PoolDetails/PoolDetails.styled.tsx
> +export const Keyword = styled.div`
Same would go on the keywords, I think the gray is kinda hiding the info and the black text on gray background is kinda doomish. This might look better with the theme orange & white text

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/components/upload/Upload.tsx
> +  accept,
```suggestion
  accept,
  disabled = false,
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/containers/modals/card-details/CardDetails.tsx
> +              {transformFromWei(cap, tokenDecimals)} {tokenName || 'TARA'}
Same as above, assign fallback to tokenName

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/models/Leaderboard.ts
> +}
EOF newline

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/pages/AddHypePool/AddHypePool.effects.tsx
> +    console.log('image url: ', imageUrl);
🧹

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +                    subtitle="TARA claimed"
```suggestion
                    subtitle={`${poolTokenName} claimed`}
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +                    subtitle="TARA awarded"
```suggestion
                    subtitle={`${poolTokenName} awarded`}
```

2023-06-26 09:53 UTC, VargaElod23 commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +  cid: CID | string;
isn't this supposed to return a CID every time?

2023-06-26 09:53 UTC, VargaElod23 commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +  cid: CID | string;
If we want to convert, let's convert all to string or keep all as CID. Wouldn't that keep things tidier?

2023-06-26 09:53 UTC, VargaElod23 commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +      console.log('Image uploaded: ', uploaded);
We could use `Logger` here instead as I'd prefer to keep these entries :)

2023-06-26 09:59 UTC, Malak67 commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +  cid: CID | string;
No because we need it as a string only for the image upload. Because it looks different compared to the other endpoint with the description. So for that we keep the CID. But I don`t see a problem having this or.

2023-06-26 13:22 UTC, Malak67 commented on services/client/src/components/card/Card.tsx
> +                {transformFromWei(cap, tokenDecimals)} {tokenName || 'TARA'}
Yeah, but currently this might a different issue altogether. Might need to handle it in another PR after we decide on the corect approach.

2023-06-26 13:49 UTC, rattrap requested changes

2023-06-26 13:49 UTC, rattrap commented on services/client/src/models/Leaderboard.ts
> +  totalimpressions: number;
`totalimpressions` -> `totalImpressions`

2023-06-26 13:49 UTC, rattrap commented on services/client/src/pages/AddHypePool/AddHypePool.effects.tsx
> +
No need for this. We can just use `uploadedImageUrl`

2023-06-26 13:49 UTC, rattrap commented on services/client/src/pages/AddHypePool/DetailsForm/DetailsForm.tsx
> +  setSelectedImage: Dispatch<any>;
I don't know what this `Dispatch<any>` is but shouldn't it be an anonymous method?

2023-06-26 13:49 UTC, rattrap commented on services/client/src/pages/AddHypePool/DetailsForm/DetailsForm.tsx
> +            This is not mandatory but we recommend uploading an image to represent your project
`an image to represent your project` -> `an image that represents your project`

2023-06-26 13:49 UTC, rattrap commented on services/client/src/pages/AddHypePool/DetailsForm/DetailsForm.tsx
> +                  console.log(event.target.files[0]);
Remove the console.log

2023-06-26 20:28 UTC, rattrap requested changes

2023-06-26 20:28 UTC, rattrap commented on services/client/src/containers/redeem/ImpressionsList.tsx
> +                {transformFromWei(Number(item.rewards), tokenDecimals)} {symbol}
Transforming this to a number might overflow

2023-06-26 20:28 UTC, rattrap commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +    : null;
Transforming `poolStats.tokensAwarded` and `poolStats.tokensClaimed` to numbers might overflow

2023-06-26 20:28 UTC, rattrap commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +            <InfoValue key={`${startDate}-${Date.now()}`}>{startedAt}</InfoValue>
Adding `Date.now()` here might confuse React

2023-06-26 20:28 UTC, rattrap commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +            <InfoValue key={`${endDate}-${Date.now()}`}>{endsAt}</InfoValue>
Same as above ^

2023-06-26 20:28 UTC, rattrap commented on services/client/src/pages/PoolDetails/PoolDetails.tsx
> +            )}
Same as above ^

2023-06-27 06:19 UTC, rattrap approved these changes

2023-06-27 06:19 UTC, merged