Feat/21
Taraxa-project/hype pull request #25
Opened 2022-06-06 15:06 UTC by VargaElod23

2022-06-07 06:39 UTC, Malak67 approved these changes
Maybe it would be a good idea to add the styled components inside a subfolder of components (maybe called styled) to differentiate them from the reusable components. Another idea would be to add it in the name, ex: header.styled.ts. Just a thought.

2022-06-07 13:33 UTC, VargaElod23 commented
@farebord pls fix conflicts

2022-06-07 14:08 UTC, farebord commented
> Maybe it would be a good idea to add the styled-components inside a subfolder of components (maybe called styled) to differentiate them from the reusable components. Another idea would be to add it in the name, ex: header.styled.ts. Just a thought.

@Malak67 I totally agree with this, and I think the original idea was to keep styled-components in the same file until they are used in another folder. 
If they become reusable we moved them into the components or styled folder.

2022-06-09 10:50 UTC, VargaElod23 commented
@farebord any update on this one?

2022-06-10 10:08 UTC, VargaElod23 commented
@farebord  The Rebase went sideways, I think. `root/client/` shouldn't exist, logic should be inside `services/client`. Also, I see that the page is created very specifically for the form that it handles. I would recreate it with much more attention to atomicity and reusability. Also, the form is not handled, please implement it with an actual login until the backend API is being called.

2022-06-10 10:11 UTC, Malak67 requested changes
@farebord Please fix the merge issue as per @VargaElod23 mentioned!

2022-06-10 14:05 UTC, Malak67 commented on services/client/src/pages/AddHypePool/AddHypePool.tsx
> +const Wrapper = styled.div`
One small thing, I would move all the styles into a separate file called AddHypePool.styled.tsx so we separate the logic.

2022-06-10 14:07 UTC, farebord commented on services/client/src/pages/AddHypePool/AddHypePool.tsx
> +const Wrapper = styled.div`
Sure! Working on that!

2022-06-10 14:19 UTC, Malak67 approved these changes

2022-06-10 14:21 UTC, merged