Feat/replacing wagmi
Taraxa-project/hype pull request #269
Opened 2023-07-17 13:01 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #261 .

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [x] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-07-24 12:35 UTC, VargaElod23 submitted a review, later dismissed
LGTM 👍🏼

2023-08-01 09:35 UTC, rattrap requested changes

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useEscrow.tsx
> +            gasLimit: BigNumber.from(9999999),
We can remove this.

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useEscrow.tsx
> +            gasLimit: BigNumber.from(9999999),
Remove fixed gasLimit

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useEscrow.tsx
> +            value: amount,
If this is an ERC20 token, we don't need to set the value

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useEscrow.tsx
> +    [provider, deposit, erc20ABI, hideLoadingModal, showLoading, showNotificationModal],
Why does this depend on the deposit callback?

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useEscrow.tsx
> +      spender: string,
I think the spender is always our Escrow contract

2023-08-01 09:35 UTC, rattrap commented on services/client/src/hooks/useHypePools.tsx
> +  word: string;
Don't forget to rename this

2023-08-01 09:35 UTC, rattrap commented on services/client/src/pages/AddHypePool/Summary/Summary.effects.tsx
> +          await approve(account, createdPoolIndex, amount, rewards.tokenAddress as AddressType);
We still need to call the deposit function even if it's a custom token

2023-08-01 09:35 UTC, rattrap commented on services/client/src/pages/PoolDetails/PoolDetails.effects.tsx
> +          await approve(account, poolId, amount, pool?.tokenAddress as AddressType);
Same. Still need to call deposit after approval

2023-08-01 11:04 UTC, rattrap approved these changes

2023-08-01 11:31 UTC, VargaElod23 approved these changes

2023-08-01 11:32 UTC, merged