Created logic for reading new telegram groups and no of messages
Taraxa-project/hype pull request #279
Opened 2023-08-13 12:51 UTC by Malak67

# Generic Pull Request template

## Linked issue

Please link the issue:

ex. Closes #278 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.
- [ ] The changes impact front-end.

## For changes impacting frontend

Please leave some screenshots/video recordings of the newly implemented interface and the Figma link for its initial design.

### Screenshots/ recordings

=> Multimedia here.

### Figma link

=> Figma link here.

## Description

Please provide a short description about what the PR contains.

## Funny gif

Leave a funny gif for faster review.

2023-08-14 15:53 UTC, rattrap requested changes

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/abi/GroupManagerFacet.abi.json
> +{
Let's either use this interface:
https://github.com/Taraxa-project/echo/blob/main/smart-contracts/contracts/interfaces/IIngesterDataGathering.sol

Or just the event signature.

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/tsconfig.json
> +    "src/abi/GroupManagerFacet.abi.json"
Shouldn't need to add this here as we have `resolveJsonModule` enabled

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +      this.httpService.get<any>(path).pipe(
Why not just use the `ipClient` to get the file?

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/migrations/1691929138307-TelegramGroupUpdates.ts
> +      `ALTER TABLE "group" ALTER COLUMN "created_at" DROP DEFAULT`,
I don't think this is correct.

`ALTER TABLE "group" DROP COLUMN "created_at";`

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/migrations/1691929138307-TelegramGroupUpdates.ts
> +      `ALTER TABLE "group" ALTER COLUMN "created_at" SET DEFAULT now()`,
`ALTER TABLE "group" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/entities/group.entity.ts
> -export class Group extends BaseEntity implements IGroup {
Maybe we can remove the interface file too

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/entities/group.entity.ts
>    groupId?: number;
Shouldn't be optional I think. Can't do anything without this

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/entities/group.entity.ts
> +  totalMessages?: number;
Let's not make these nullable but make the default value to be 0

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/entities/group.entity.ts
> +  updatedAt?: Date;
These should not be optional

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/modules/group/group.module.ts
> +  }
Don't really like this static value. Let's just split this method and the cron from the service class and create a new `ingester-task.service.ts`

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/modules/group/ingester.service.ts
> +  @Cron('0 0 * * SUN')
This will run on all instances

2023-08-14 15:53 UTC, rattrap commented on services/hype-backend/src/modules/group/ingester.service.ts
> +        existingGroup.totalMessages += chatInfo.totalMessages;
You are overwriting the data below:

2023-08-14 18:51 UTC, Malak67 commented on services/hype-backend/src/modules/ipfs/ipfs.service.ts
> +      this.httpService.get<any>(path).pipe(
I tested with `ipfsClient.cat` but for some reason it didn`t worked and I find the clasig http get easier to interpret.
Also the ipfs-http-client is deprecated so we might need to move to Helia soon.

2023-08-24 14:06 UTC, rattrap commented
Current contract on mainnet: `0x22B74CA2808BFD30C2FA64dEda0Cfe0D2Da07f0C`

2023-08-25 09:54 UTC, rattrap approved these changes

2023-08-25 09:54 UTC, merged